def palindrome(s, k):
    # Define the pairs of characters that form palindromes
    pali_pairs = [('A', 'T'), ('T', 'A'), ('G', 'C'), ('C', 'G')]

    # Iterate through all substrings of length k in s
    for i in range(len(s) - k + 1):
        test = s[i:i+k]  # Get the current substring

        # Check if all pairs of characters in the substring form palindromes
        if all((test[j], test[k-j-1]) in pali_pairs for j in range(k)):
            print(i+1, k)  # Print the starting index (i+1) and length (k)

string = 'TATAAACATCTGCCAGATGATGACCTGTTTTGTCAGCAGGATAAGCAGCGCCCGGCTATTTCGCCTTTTCGCTTTACAATACAGGAGGTGTCTTCGCCAAAGTAGGAGCAACCATGCTGCGGAATCACCCAGCGGGATGAATAGGCTCTCTTACCCTCTCGTCCAGGGGCCTGATCCAAGGGCTGATATATTGTGACTTTCCTCGGCGTTGTATTTACTGTCGCATCTGTGGGCTAGAACACAGACGATAATCACCTCTAGCGTTGAACGCAGGACCTCAGTTCGACTACGGGGCGGTCTAAACTAACGGCAACTAAGCCACGAATCAGTTGGTCACGCGCTTGCCGTACCATAGGGAGAATGACGAGTTCAGACAGAGACATCCCATATAACCCTGTTATGTCAAACAGTGTGGCTAAGCGACTTATAATGATCCTTAACGTTCCGTTGCTCCAGATATCTGGCCAATAGATCCTCCTCTGCGGGATCATACGAAACGGTCGCCAGGCCCCTACGGCTCGTAACTCTATAAGGGGATGCACCTCTAGAAGCCCTACCAATTTCGCTTCACCAACCAAAGAAAAGCGACGTATGTTGTGCAACTTAGTCCTCCGCAACCGTTACGAGGTGACTTAGTTTGAAGAAAGGCTTACACCAGTTCCGAAGTATCGCTTGACTGTCACGCCAACACCTTTCATGCTTTGACTCCATCGTGCAGGCCCCTTCGTCATCCACAACGCAGTACTATCCAGGCGCCCTGTTCACTACGCAAATTTTGACTTGATTCGGTATTTTCTGTTGTAGTTGGCGCCAGCGACTCTGACACACGGACACTCCTTGTGGGTATGATTTTTCCTGTGAGGATGTTATGTAGTGCCTGATCATTACGGAGGGGTGAAGTAATGCATTGGCATAT'
for i in range(4,14,2):
	palindrome(string, i)
